#!/bin/bash

echo "🔧 修复 npm 权限问题..."
echo "请运行以下命令（需要输入密码）："
echo ""
echo "sudo chown -R $(whoami) ~/.npm"
echo ""
echo "或者直接运行："
echo "sudo chown -R 501:20 ~/.npm"
echo ""
echo "然后运行："
echo "npm cache clean --force"
echo ""
echo "=========================================="
echo ""
echo "🐳 启动 Docker..."
echo "请打开 Docker Desktop 应用程序"
echo "等待 Docker 完全启动后，运行："
echo "docker ps"
echo ""
echo "=========================================="
echo ""
echo "✅ 修复完成后，运行："
echo "npm install"
echo "npm install bcryptjs @types/bcryptjs"
echo "docker-compose up -d"
echo "npm run db:generate"
echo "npm run db:push"
echo "npm run db:seed"
echo "npm run dev"

