import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const shops = [
  // Los Angeles
  {
    name: 'Blue Bottle Coffee',
    address: '582 Mateo St, Los Angeles, CA 90013',
    city: 'Los Angeles',
    latitude: 34.0522,
    longitude: -118.2437,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Intelligentsia Coffee',
    address: '3922 Sunset Blvd, Los Angeles, CA 90029',
    city: 'Los Angeles',
    latitude: 34.0908,
    longitude: -118.2836,
    rating: 4.6,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting'],
    features: { noise: 3, outlets: 4, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Verve Coffee Roasters',
    address: '8925 Melrose Ave, West Hollywood, CA 90069',
    city: 'Los Angeles',
    latitude: 34.0814,
    longitude: -118.3848,
    rating: 4.4,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet', 'good lighting'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 3, lighting: 4, privacy: 2 },
  },
  {
    name: 'Café Dulcé',
    address: '1820 W Sunset Blvd, Los Angeles, CA 90026',
    city: 'Los Angeles',
    latitude: 34.0775,
    longitude: -118.2656,
    rating: 4.3,
    priceLevel: 2,
    tags: ['wifi', 'outlets'],
    features: { noise: 4, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 2 },
  },
  {
    name: 'Stumptown Coffee Roasters',
    address: '806 S Santa Fe Ave, Los Angeles, CA 90021',
    city: 'Los Angeles',
    latitude: 34.0378,
    longitude: -118.2314,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 4, lighting: 4, privacy: 3 },
  },
  {
    name: 'Alfred Coffee',
    address: '8428 Melrose Pl, Los Angeles, CA 90069',
    city: 'Los Angeles',
    latitude: 34.0814,
    longitude: -118.3728,
    rating: 4.2,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting'],
    features: { noise: 3, outlets: 4, wifi: 4, seating: 3, lighting: 5, privacy: 2 },
  },
  {
    name: 'Coffee Commissary',
    address: '801 N Fairfax Ave, Los Angeles, CA 90046',
    city: 'Los Angeles',
    latitude: 34.0836,
    longitude: -118.3611,
    rating: 4.4,
    priceLevel: 2,
    tags: ['wifi', 'outlets', 'quiet', 'private seating'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 5, lighting: 4, privacy: 4 },
  },
  {
    name: 'Café Gratitude',
    address: '639 N Larchmont Blvd, Los Angeles, CA 90004',
    city: 'Los Angeles',
    latitude: 34.0764,
    longitude: -118.3236,
    rating: 4.3,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting'],
    features: { noise: 3, outlets: 3, wifi: 4, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'La Colombe Coffee',
    address: '8400 Sunset Blvd, West Hollywood, CA 90069',
    city: 'Los Angeles',
    latitude: 34.0908,
    longitude: -118.3728,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 4, lighting: 4, privacy: 3 },
  },
  {
    name: 'Go Get Em Tiger',
    address: '230 N Larchmont Blvd, Los Angeles, CA 90004',
    city: 'Los Angeles',
    latitude: 34.0736,
    longitude: -118.3236,
    rating: 4.6,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet', 'good lighting'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Café Los Feliz',
    address: '1728 N Vermont Ave, Los Angeles, CA 90027',
    city: 'Los Angeles',
    latitude: 34.1025,
    longitude: -118.2925,
    rating: 4.2,
    priceLevel: 2,
    tags: ['wifi', 'outlets'],
    features: { noise: 4, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 2 },
  },
  {
    name: 'Republique',
    address: '624 S La Brea Ave, Los Angeles, CA 90036',
    city: 'Los Angeles',
    latitude: 34.0636,
    longitude: -118.3444,
    rating: 4.7,
    priceLevel: 4,
    tags: ['wifi', 'outlets', 'good lighting', 'private seating'],
    features: { noise: 2, outlets: 4, wifi: 4, seating: 5, lighting: 5, privacy: 5 },
  },
  {
    name: 'Café de Leche',
    address: '5000 York Blvd, Los Angeles, CA 90042',
    city: 'Los Angeles',
    latitude: 34.1158,
    longitude: -118.2014,
    rating: 4.4,
    priceLevel: 2,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 3, lighting: 4, privacy: 3 },
  },
  {
    name: 'Café Tropical',
    address: '2900 Sunset Blvd, Los Angeles, CA 90026',
    city: 'Los Angeles',
    latitude: 34.0908,
    longitude: -118.2656,
    rating: 4.1,
    priceLevel: 2,
    tags: ['wifi', 'outlets'],
    features: { noise: 4, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 2 },
  },
  {
    name: 'Café Stella',
    address: '3932 Sunset Blvd, Los Angeles, CA 90029',
    city: 'Los Angeles',
    latitude: 34.0908,
    longitude: -118.2836,
    rating: 4.3,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting', 'private seating'],
    features: { noise: 3, outlets: 4, wifi: 4, seating: 4, lighting: 5, privacy: 4 },
  },
  // San Francisco
  {
    name: 'Blue Bottle Coffee',
    address: '315 Linden St, San Francisco, CA 94102',
    city: 'San Francisco',
    latitude: 37.7749,
    longitude: -122.4194,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Ritual Coffee Roasters',
    address: '1026 Valencia St, San Francisco, CA 94110',
    city: 'San Francisco',
    latitude: 37.7594,
    longitude: -122.4214,
    rating: 4.6,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet', 'good lighting'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Sightglass Coffee',
    address: '270 7th St, San Francisco, CA 94103',
    city: 'San Francisco',
    latitude: 37.7749,
    longitude: -122.4094,
    rating: 4.4,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 4, lighting: 4, privacy: 3 },
  },
  {
    name: 'Four Barrel Coffee',
    address: '375 Valencia St, San Francisco, CA 94103',
    city: 'San Francisco',
    latitude: 37.7649,
    longitude: -122.4214,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet', 'good lighting'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Philz Coffee',
    address: '3101 24th St, San Francisco, CA 94110',
    city: 'San Francisco',
    latitude: 37.7524,
    longitude: -122.4144,
    rating: 4.3,
    priceLevel: 2,
    tags: ['wifi', 'outlets'],
    features: { noise: 3, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 2 },
  },
  {
    name: 'Andytown Coffee Roasters',
    address: '3655 Lawton St, San Francisco, CA 94122',
    city: 'San Francisco',
    latitude: 37.7594,
    longitude: -122.4894,
    rating: 4.5,
    priceLevel: 2,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 3, lighting: 4, privacy: 3 },
  },
  {
    name: 'Réveille Coffee Co.',
    address: '4076 18th St, San Francisco, CA 94114',
    city: 'San Francisco',
    latitude: 37.7594,
    longitude: -122.4344,
    rating: 4.4,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting'],
    features: { noise: 3, outlets: 4, wifi: 4, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Equator Coffees',
    address: '986 Market St, San Francisco, CA 94102',
    city: 'San Francisco',
    latitude: 37.7849,
    longitude: -122.4094,
    rating: 4.4,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 4, lighting: 4, privacy: 3 },
  },
  {
    name: 'Café Claude',
    address: '7 Claude Ln, San Francisco, CA 94108',
    city: 'San Francisco',
    latitude: 37.7874,
    longitude: -122.4044,
    rating: 4.2,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'private seating'],
    features: { noise: 3, outlets: 3, wifi: 4, seating: 4, lighting: 4, privacy: 5 },
  },
  {
    name: 'Workshop Café',
    address: '180 Montgomery St, San Francisco, CA 94104',
    city: 'San Francisco',
    latitude: 37.7894,
    longitude: -122.4014,
    rating: 4.6,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'quiet', 'private seating'],
    features: { noise: 2, outlets: 5, wifi: 5, seating: 5, lighting: 4, privacy: 4 },
  },
  {
    name: 'Café du Soleil',
    address: '200 Fillmore St, San Francisco, CA 94117',
    city: 'San Francisco',
    latitude: 37.7724,
    longitude: -122.4344,
    rating: 4.1,
    priceLevel: 2,
    tags: ['wifi', 'outlets'],
    features: { noise: 4, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 2 },
  },
  {
    name: 'The Mill',
    address: '736 Divisadero St, San Francisco, CA 94117',
    city: 'San Francisco',
    latitude: 37.7754,
    longitude: -122.4374,
    rating: 4.5,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting'],
    features: { noise: 3, outlets: 4, wifi: 4, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Café Trieste',
    address: '601 Vallejo St, San Francisco, CA 94133',
    city: 'San Francisco',
    latitude: 37.7984,
    longitude: -122.4074,
    rating: 4.3,
    priceLevel: 2,
    tags: ['wifi', 'outlets', 'quiet'],
    features: { noise: 2, outlets: 3, wifi: 4, seating: 3, lighting: 3, privacy: 4 },
  },
  {
    name: 'Café St. Jorge',
    address: '3438 Mission St, San Francisco, CA 94110',
    city: 'San Francisco',
    latitude: 37.7444,
    longitude: -122.4214,
    rating: 4.4,
    priceLevel: 2,
    tags: ['wifi', 'outlets', 'quiet', 'good lighting'],
    features: { noise: 2, outlets: 4, wifi: 5, seating: 4, lighting: 5, privacy: 3 },
  },
  {
    name: 'Café Réveille Fillmore',
    address: '2007 Fillmore St, San Francisco, CA 94115',
    city: 'San Francisco',
    latitude: 37.7874,
    longitude: -122.4344,
    rating: 4.3,
    priceLevel: 3,
    tags: ['wifi', 'outlets', 'good lighting', 'private seating'],
    features: { noise: 3, outlets: 4, wifi: 4, seating: 4, lighting: 5, privacy: 4 },
  },
]

async function main() {
  console.log('Starting seed data...')

  for (const shop of shops) {
    await prisma.shop.create({
      data: shop,
    })
  }

  console.log(`Created ${shops.length} coffee shops`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

